language: c
dist: bionic
git:
  submodules: false
addons:
  apt:
    packages:
    - bzip2
    - lzip
    - zstd
before_install:
  - sudo git clone https://github.com/firasuke/mussel
  - cd mussel
install:
  - sudo dash mussel.sh
